name: Release
on:
  push:
    branches:
      - main

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: ReactNepaliDates
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
